<?php

namespace BarberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceEventRepository extends EntityRepository
{
}
