<?php

namespace BarberBundle\Repository;

use BarberBundle\Entity\Service;
use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /*
     * @TODO - move to some kind of Manager class
     */
    public function save(Service $service)
    {
        $this->getEntityManager()->persist($service);

        return $service;
    }

}
